### ISSUE TITLE
Add explicit concept sets used in the rules

### ISSUE THREAD

**Issue by rkboyce** [dbmi-pitt/iDIA_Rules#1]
With the goal of helping users to set up and run the rule engine with ether the simulated population (e.g., to validate their set up) or against their own population - please create a folder under the top level of the repository for the concept set protocols and the list of concept ids for each concept set.

**Comment by samuelrosko** [comment]
I created a new folder in the root directory titled "protocols_and_concept_sets" that contains each protocol that we have implemented and their associated concept sets.
